name: CI Workflow

on:
  push:
    branches:
      - staging
  pull_request:
    types: closed
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ganti dengan versi Node.js yang sesuai

      - name: Install Node.js dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Sync staging to build
        run: |
          git push origin -d build
          git checkout -b build
          git merge build
          git push origin build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync staging to main
        run: |
          git fetch
          git checkout -b main
          git pull origin main
          git push origin main
          git pull origin build
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
