# name: CICD to Production & Cpanel

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Git
#         run: |
#           git config --global user.name 'GitHub Actions'
#           git config --global user.email 'actions@github.com'

#       - name: Sync main to production
#         run: |
#           git push origin -d production
#           git checkout -b production
#           git merge main
#           git push origin production
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '8.2' # Ganti dengan versi PHP yang sesuai

#       - name: Install Composer
#         run: composer install --no-dev --optimize-autoloader

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16' # Ganti dengan versi Node.js yang sesuai

#       - name: Install Node.js dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build

#       - name: Install lftp
#         run: sudo apt-get install lftp

#       - name: Deploy to cPanel FTP
#         env:
#           FTP_SERVER: ${{ secrets.FTP_SERVER }}
#           FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#           FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#         run: |
#           lftp -f "
#           set ssl:verify-certificate no
#           open $FTP_SERVER
#           user $FTP_USERNAME $FTP_PASSWORD
#           mirror -R ./ /
#           bye
#           "
