name: CI Workflow Main

workflow_run:
  workflows: ['CI Workflow Build']
  types:
    - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Sync build to main
        run: |
          git fetch
          git checkout main
          git merge build --no-ff -m "Merge build branch into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
